### ISSUE TITLE
CSV lines with an offset more than 9 numbers won't decode

### ISSUE THREAD

**Issue by dafitius** [s4xon/rpkgtools#1]
CSV lines with an offset more than 9 numbers won't decode.

Working:
"Offset: 548.044.798, Length: 349.584"
"Offset: 548.397.056, Length: 258.048"

Not working:
"Offset: 6.425.514.335, Length: 16.384"
"Offset: 6.337.239.335, Length: 174.792"

**Comment by s4xon** [comment]
The issue seems to be with my 'assumption' in the code of numerical locale and that the offsets are integers and have 'commas' in the numerical string. I see that you have 'periods' instead, so I'll update the code to allow for parsing both ',' and '.'.

**Comment by s4xon** [comment]
Should be resolved now I just tested it.

Test outputs:

"8:22:59.9831834 AM","hitman2.exe","9200","ReadFile","C:\Program Files (x86)\Steam\steamapps\common\HITMAN2\Runtime\chunk0patch1.rpkg","SUCCESS","Offset: 1.100.101.946.206, Length: 4.096, Priority: Normal"

decoded to:
offset: 1100101946206
length: 4096

"8:22:59.9831834 AM","hitman2.exe","9200","ReadFile","C:\Program Files (x86)\Steam\steamapps\common\HITMAN2\Runtime\chunk0patch1.rpkg","SUCCESS","Offset: 101,100,101,946,206, Length: 4.096, Priority: Normal"

decoded to:
offset: 101100101946206
length: 4096

**Comment by s4xon** [comment]
Should be resolved, updated the code, I just tested it.
Will update the release to v1.01.

Test outputs:

"8:22:59.9831834 AM","hitman2.exe","9200","ReadFile","C:\Program Files (x86)\Steam\steamapps\common\HITMAN2\Runtime\chunk0patch1.rpkg","SUCCESS","Offset: 1.100.101.946.206, Length: 4.096, Priority: Normal"

decoded to:
offset: 1100101946206
length: 4096

"8:22:59.9831834 AM","hitman2.exe","9200","ReadFile","C:\Program Files (x86)\Steam\steamapps\common\HITMAN2\Runtime\chunk0patch1.rpkg","SUCCESS","Offset: 101,100,101,946,206, Length: 4.096, Priority: Normal"

decoded to:
offset: 101100101946206
length: 4096
